source.. = src/
output.. = target/classes/
bin.includes = META-INF/,\
               .,\
               OSGI-INF/,\
               sql/,\
               README.md
src.includes = sql/,\
               README.md,\
               pom.xml,\
               build.properties
